import { cleanup,render,screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import App from "./App";
beforeEach(()=>{localStorage.clear();vi.spyOn(window,"scrollTo").mockImplementation(()=>undefined);vi.spyOn(URL,"createObjectURL").mockReturnValue("blob:test");vi.spyOn(URL,"revokeObjectURL").mockImplementation(()=>undefined);Object.defineProperty(window,"confirm",{value:vi.fn(()=>true),configurable:true})});afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("Suno Prompt Apothecary",()=>{
 it("offers a beautiful desktop installation path",async()=>{const user=userEvent.setup();render(<App/>);expect(screen.getByRole("button",{name:/Install the Apothecary/i})).toBeTruthy();await user.click(screen.getByRole("button",{name:/Install the Apothecary/i}));expect(screen.getByText(/Open the browser menu and choose Install app/i)).toBeTruthy()});
 it("blends ingredients and seals a versioned recipe",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:/Norse Boom Bap/i}));await user.click(screen.getByRole("button",{name:/Sacred Sensuality/i}));await user.type(screen.getByLabelText("Formula name"),"Freya After Midnight");await user.click(screen.getByRole("button",{name:/Seal in the Grimoire/i}));const vault=JSON.parse(localStorage.getItem("suno-apothecary-v1")||"{}");expect(vault.recipes[0].title).toBe("Freya After Midnight");expect(vault.recipes[0].versions[0].prompt).toContain("Nordic ritual boom bap")});
 it("adds a custom ingredient",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:"Ingredient Cabinet"}));await user.type(screen.getByLabelText("Ingredient name"),"Moonlit Bass");await user.type(screen.getByLabelText("Ingredient phrase"),"sub bass moving like black water");await user.click(screen.getByRole("button",{name:/Bottle this essence/i}));expect(screen.getByText("Moonlit Bass")).toBeTruthy()});
 it("opens every chamber",async()=>{const user=userEvent.setup();render(<App/>);for(const name of ["Ingredient Cabinet","Recipe Grimoire","Experiment Chronicle","Vocal Splitter","Private Vault","The Cauldron"]){await user.click(screen.getByRole("button",{name}));expect(screen.getByRole("heading",{name:name==="The Cauldron"?/Distill sound/:name,level:1})).toBeTruthy()}})
});
