import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, Beaker, BookOpen, Check, Copy, Download, ExternalLink, FlaskConical, Heart, History, Import, Menu, Plus, Save, Scissors, Search, Sparkles, Star, Trash2, X } from "lucide-react";
import { ingredientKinds, type Ingredient, type IngredientKind, type Rating, type Recipe, type Vault } from "./types";
import { exportVault, importVault, loadVault, makeId, saveVault } from "./vault";

type View="cauldron"|"ingredients"|"recipes"|"history"|"splitter"|"vault";
const views:[View,string,typeof Beaker][]=[["cauldron","The Cauldron",FlaskConical],["ingredients","Ingredient Cabinet",Beaker],["recipes","Recipe Grimoire",BookOpen],["history","Experiment Chronicle",History],["splitter","Vocal Splitter",Scissors],["vault","Private Vault",Archive]];
const emptyDraft={title:"",collection:"Sisters of Freya",tags:"",customText:""};
const joinPrompt=(items:Ingredient[],custom:string)=>[...items.filter(i=>i.kind!=="Exclusion").map(i=>i.phrase),custom.trim()].filter(Boolean).join(", ");
const joinExclusions=(items:Ingredient[])=>items.filter(i=>i.kind==="Exclusion").map(i=>i.phrase).join(", ");
const avg=(recipe:Recipe)=>{const rated=recipe.versions.filter(v=>v.rating);return rated.length?rated.reduce((sum,v)=>sum+(v.rating?.overall||0),0)/rated.length:0};

export default function App(){
 const [vault,setVault]=useState<Vault>(loadVault); const [view,setView]=useState<View>("cauldron"); const [nav,setNav]=useState(false);
 const [selected,setSelected]=useState<string[]>([]); const [draft,setDraft]=useState(emptyDraft); const [query,setQuery]=useState(""); const [kind,setKind]=useState<IngredientKind|"All">("All");
 const [editing,setEditing]=useState<Recipe|null>(null); const [compare,setCompare]=useState<string[]>([]); const [notice,setNotice]=useState(""); const importRef=useRef<HTMLInputElement>(null);
 const [installPrompt,setInstallPrompt]=useState<(Event&{prompt:()=>Promise<void>;userChoice:Promise<unknown>})|null>(null);
 useEffect(()=>saveVault(vault),[vault]);
 useEffect(()=>{const receive=(event:Event)=>{event.preventDefault();setInstallPrompt(event as Event&{prompt:()=>Promise<void>;userChoice:Promise<unknown>})};window.addEventListener("beforeinstallprompt",receive);return()=>window.removeEventListener("beforeinstallprompt",receive)},[]);
 const ingredients=useMemo(()=>vault.ingredients.filter(i=>(kind==="All"||i.kind===kind)&&(`${i.name} ${i.phrase} ${i.notes}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.kind.localeCompare(b.kind)),[vault.ingredients,query,kind]);
 const selectedItems=selected.map(id=>vault.ingredients.find(i=>i.id===id)).filter(Boolean) as Ingredient[];
 const prompt=joinPrompt(selectedItems,draft.customText); const exclusions=joinExclusions(selectedItems);
 const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),1800)};
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const copy=async(text:string)=>{await navigator.clipboard?.writeText(text);flash("Copied to your clipboard")};
 const install=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);flash("The Apothecary is joining your desktop")}else flash("Open the browser menu and choose Install app")};
 const saveRecipe=()=>{if(!draft.title.trim()||!prompt)return;const now=new Date().toISOString();const recipe:Recipe={id:editing?.id||makeId("recipe"),title:draft.title.trim(),collection:draft.collection,tags:draft.tags.split(",").map(x=>x.trim()).filter(Boolean),ingredientIds:selected,customText:draft.customText,createdAt:editing?.createdAt||now,updatedAt:now,favorite:editing?.favorite||false,versions:[{id:makeId("version"),number:(editing?.versions.length||0)+1,prompt,exclusions,note:editing?"Refined formula":"First distillation",createdAt:now},...(editing?.versions||[])]};setVault(v=>({...v,ingredients:v.ingredients.map(i=>selected.includes(i.id)?{...i,uses:i.uses+1}:i),recipes:editing?v.recipes.map(r=>r.id===editing.id?recipe:r):[recipe,...v.recipes]}));setEditing(null);setSelected([]);setDraft(emptyDraft);flash("Formula sealed in the Grimoire")};
 const openRecipe=(recipe:Recipe)=>{setEditing(recipe);setSelected(recipe.ingredientIds);setDraft({title:recipe.title,collection:recipe.collection,tags:recipe.tags.join(", "),customText:recipe.customText});setView("cauldron");window.scrollTo({top:0,behavior:"smooth"})};
 const addIngredient=(data:Omit<Ingredient,"id"|"createdAt"|"uses"|"favorite">)=>setVault(v=>({...v,ingredients:[{...data,id:makeId("ingredient"),createdAt:new Date().toISOString(),uses:0,favorite:false},...v.ingredients]}));
 const rate=(recipeId:string,versionId:string,rating:Rating,note:string,url:string)=>setVault(v=>({...v,recipes:v.recipes.map(r=>r.id!==recipeId?r:{...r,updatedAt:new Date().toISOString(),versions:r.versions.map(ver=>ver.id===versionId?{...ver,rating,outcomeNote:note,sunoUrl:url}:ver)})}));
 return <div className="app-shell">
  <aside className={nav?"open":""}><button className="brand" onClick={()=>setView("cauldron")}><span>ᛉ</span><div><strong>Suno Prompt</strong><em>APOTHECARY</em></div></button><nav>{views.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setNav(false)}}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="vault-mark"><i/><span>PRIVATE LOCAL VAULT</span><small>{vault.recipes.length} formulas · {vault.ingredients.length} ingredients</small></div></aside>
  {nav&&<button className="scrim" aria-label="Close menu" onClick={()=>setNav(false)}/>}<main><header className="topbar"><button className="menu" aria-label="Open menu" onClick={()=>setNav(true)}><Menu/></button><span>THE NINTH REALM · PRIVATE EDITION</span><div className="top-actions"><label><Search size={15}/><input aria-label="Search ingredients" value={query} placeholder="Search the cabinet" onChange={e=>setQuery(e.target.value)}/></label><button className="install-button" onClick={install}><Download size={14}/><span>Install app</span></button></div></header>
  {view==="cauldron"&&<Cauldron selected={selectedItems} ingredients={ingredients} selectedIds={selected} toggle={toggle} draft={draft} setDraft={setDraft} prompt={prompt} exclusions={exclusions} save={saveRecipe} copy={copy} install={install} editing={editing} clear={()=>{setEditing(null);setSelected([]);setDraft(emptyDraft)}}/>}
  {view==="ingredients"&&<Ingredients vault={vault} setVault={setVault} query={query} kind={kind} setKind={setKind} ingredients={ingredients} add={addIngredient}/>} 
  {view==="recipes"&&<Recipes recipes={vault.recipes} open={openRecipe} copy={copy} setVault={setVault}/>} 
  {view==="history"&&<Chronicle recipes={vault.recipes} rate={rate} compare={compare} setCompare={setCompare}/>} 
  {view==="splitter"&&<Splitter/>}
  {view==="vault"&&<VaultRoom vault={vault} setVault={setVault} exportNow={()=>exportVault(vault)} importRef={importRef} importNow={async file=>{try{setVault(await importVault(file));flash("Vault restored") }catch(error){flash(error instanceof Error?error.message:"Import failed")}}}/>} 
  </main>{notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 </div>
}

function Cauldron({selected,ingredients,selectedIds,toggle,draft,setDraft,prompt,exclusions,save,copy,install,editing,clear}:{selected:Ingredient[];ingredients:Ingredient[];selectedIds:string[];toggle:(id:string)=>void;draft:typeof emptyDraft;setDraft:(d:typeof emptyDraft)=>void;prompt:string;exclusions:string;save:()=>void;copy:(s:string)=>void;install:()=>void;editing:Recipe|null;clear:()=>void}){
 return <><section className="hero"><div className="hero-copy"><span className="eyebrow">ᛉ · THE LIVING FORMULARY</span><h1>Distill sound<br/><em>into legend.</em></h1><p>Gather musical essences. Blend them with intention. Preserve every experiment until instinct becomes mastery.</p><button className="hero-install" onClick={install}><Download size={16}/><span><strong>Install the Apothecary</strong><small>Open from your desktop · works offline</small></span></button><div className="hero-stats"><span><strong>{selected.length}</strong> essences</span><span><strong>{prompt.length}</strong> characters</span><span><strong>{editing?editing.versions.length+1:1}</strong> version</span></div></div></section>
 <section className="workspace"><div className="cabinet panel"><header><div><span className="eyebrow">01 · SELECT</span><h2>Ingredient Cabinet</h2></div><small>{ingredients.length} available</small></header><div className="mini-ingredients">{ingredients.map(item=><button key={item.id} className={selectedIds.includes(item.id)?"selected":""} onClick={()=>toggle(item.id)}><span>{item.kind}</span><strong>{item.name}</strong><small>{item.phrase}</small>{selectedIds.includes(item.id)?<Check size={14}/>:<Plus size={14}/>}</button>)}</div></div>
 <div className="cauldron panel"><header><div><span className="eyebrow">02 · BLEND</span><h2>{editing?`Refine ${editing.title}`:"The Cauldron"}</h2></div>{editing&&<button className="icon" title="Cancel refinement" onClick={clear}><X size={17}/></button>}</header><label>Formula name<input value={draft.title} placeholder="Name this sonic elixir…" onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="two"><label>Collection<select value={draft.collection} onChange={e=>setDraft({...draft,collection:e.target.value})}><option>Sisters of Freya</option><option>SUBINAC</option><option>Sleep Magic</option><option>Experiments</option></select></label><label>Tags<input value={draft.tags} placeholder="norse, ambient, sacred" onChange={e=>setDraft({...draft,tags:e.target.value})}/></label></div><label>Final custom essence<textarea value={draft.customText} placeholder="Add the singular detail that makes this formula yours…" onChange={e=>setDraft({...draft,customText:e.target.value})}/></label><div className="distillation"><span>Distilled style prompt</span><p>{prompt||"Select ingredients and your formula will emerge here."}</p><button disabled={!prompt} onClick={()=>copy(prompt)}><Copy size={15}/>Copy prompt</button></div>{exclusions&&<div className="exclusions"><span>Exclude</span><p>{exclusions}</p></div>}<button className="primary" disabled={!draft.title.trim()||!prompt} onClick={save}><Save size={16}/>{editing?"Seal new version":"Seal in the Grimoire"}</button></div></section></>
}

function Ingredients({vault,setVault,kind,setKind,ingredients,add}:{vault:Vault;setVault:(v:Vault)=>void;query:string;kind:IngredientKind|"All";setKind:(k:IngredientKind|"All")=>void;ingredients:Ingredient[];add:(d:Omit<Ingredient,"id"|"createdAt"|"uses"|"favorite">)=>void}){const [form,setForm]=useState({name:"",phrase:"",kind:"Mood" as IngredientKind,notes:""});return <Page eyebrow="THE RAW MATERIALS" title="Ingredient Cabinet" subtitle="Every great prompt begins with a vocabulary that belongs to its maker."><div className="filter-row"><select aria-label="Filter ingredient kind" value={kind} onChange={e=>setKind(e.target.value as IngredientKind|"All")}><option>All</option>{ingredientKinds.map(k=><option key={k}>{k}</option>)}</select><span>{ingredients.length} essences shown</span></div><section className="ingredient-layout"><form className="ingredient-form panel" onSubmit={e=>{e.preventDefault();if(form.name&&form.phrase){add(form);setForm({name:"",phrase:"",kind:"Mood",notes:""})}}}><span className="eyebrow">CREATE AN ESSENCE</span><h2>Add to the Cabinet</h2><label>Name<input aria-label="Ingredient name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select aria-label="Ingredient category" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as IngredientKind})}>{ingredientKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Prompt phrase<textarea aria-label="Ingredient phrase" value={form.phrase} onChange={e=>setForm({...form,phrase:e.target.value})}/></label><label>Private notes<textarea aria-label="Ingredient notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary"><Plus size={15}/>Bottle this essence</button></form><div className="ingredient-grid">{ingredients.map(item=><article key={item.id}><header><span>{item.kind}</span><button aria-label={`${item.favorite?"Unfavorite":"Favorite"} ${item.name}`} onClick={()=>setVault({...vault,ingredients:vault.ingredients.map(i=>i.id===item.id?{...i,favorite:!i.favorite}:i)})}><Star size={15} fill={item.favorite?"currentColor":"none"}/></button></header><h3>{item.name}</h3><p>{item.phrase}</p>{item.notes&&<small>{item.notes}</small>}<footer><span>{item.uses} uses</span><button aria-label={`Delete ${item.name}`} onClick={()=>confirm(`Remove ${item.name}?`)&&setVault({...vault,ingredients:vault.ingredients.filter(i=>i.id!==item.id)})}><Trash2 size={14}/></button></footer></article>)}</div></section></Page>}

function Recipes({recipes,open,copy,setVault}:{recipes:Recipe[];open:(r:Recipe)=>void;copy:(s:string)=>void;setVault:(fn:(v:Vault)=>Vault)=>void}){const [filter,setFilter]=useState("");const shown=recipes.filter(r=>`${r.title} ${r.tags.join(" ")} ${r.collection}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.updatedAt.localeCompare(a.updatedAt));return <Page eyebrow="TESTED FORMULAS" title="Recipe Grimoire" subtitle="The library of everything you have imagined, refined and learned."><div className="filter-row"><label><Search size={15}/><input aria-label="Search recipes" value={filter} placeholder="Search formulas…" onChange={e=>setFilter(e.target.value)}/></label><span>{shown.length} formulas</span></div>{shown.length?<div className="recipe-grid">{shown.map(r=><article key={r.id}><header><span>{r.collection}</span><button aria-label={`${r.favorite?"Unfavorite":"Favorite"} ${r.title}`} onClick={()=>setVault(v=>({...v,recipes:v.recipes.map(x=>x.id===r.id?{...x,favorite:!x.favorite}:x)}))}><Heart size={15} fill={r.favorite?"currentColor":"none"}/></button></header><h2>{r.title}</h2><p>{r.versions[0]?.prompt}</p><div className="tags">{r.tags.map(t=><span key={t}>#{t}</span>)}</div><footer><span>{r.versions.length} versions · {avg(r).toFixed(1)||"—"} rating</span><button onClick={()=>copy(r.versions[0]?.prompt||"")}><Copy size={14}/></button><button onClick={()=>open(r)}>Refine</button></footer></article>)}</div>:<Empty title="The pages await their first formula."/>}</Page>}

function Chronicle({recipes,rate,compare,setCompare}:{recipes:Recipe[];rate:(r:string,v:string,x:Rating,n:string,u:string)=>void;compare:string[];setCompare:(x:string[])=>void}){const versions=recipes.flatMap(r=>r.versions.map(v=>({recipe:r,version:v}))).sort((a,b)=>b.version.createdAt.localeCompare(a.version.createdAt));const compared=versions.filter(x=>compare.includes(x.version.id));return <Page eyebrow="LEARN FROM THE MUSIC" title="Experiment Chronicle" subtitle="Rate the result, preserve the lesson, and let every generation sharpen the next.">{compared.length===2&&<div className="compare panel"><header><h2>Formula Comparison</h2><button onClick={()=>setCompare([])}><X size={15}/>Close</button></header><div>{compared.map(({recipe,version})=><article key={version.id}><span>{recipe.title} · V{version.number}</span><p>{version.prompt}</p><strong>{version.rating?.overall||"—"}/5</strong></article>)}</div></div>}<div className="chronicle">{versions.map(({recipe,version})=><OutcomeCard key={version.id} recipe={recipe} version={version} rate={rate} checked={compare.includes(version.id)} toggle={()=>setCompare(compare.includes(version.id)?compare.filter(x=>x!==version.id):compare.length<2?[...compare,version.id]:[compare[1],version.id])}/>)}</div>{!versions.length&&<Empty title="Create a formula, generate it in Suno, then return to record what the music taught you."/>}</Page>}
function OutcomeCard({recipe,version,rate,checked,toggle}:{recipe:Recipe;version:Recipe["versions"][number];rate:(r:string,v:string,x:Rating,n:string,u:string)=>void;checked:boolean;toggle:()=>void}){const [rating,setRating]=useState<Rating>(version.rating||{overall:3,adherence:3,originality:3,sound:3});const [note,setNote]=useState(version.outcomeNote||"");const [url,setUrl]=useState(version.sunoUrl||"");return <article className="outcome panel"><header><div><span>{recipe.collection} · VERSION {version.number}</span><h2>{recipe.title}</h2></div><label className="compare-check"><input type="checkbox" checked={checked} onChange={toggle}/>Compare</label></header><p className="prompt-quote">{version.prompt}</p><div className="ratings">{(["overall","adherence","originality","sound"] as const).map(k=><label key={k}><span>{k} · {rating[k]}</span><input aria-label={`${recipe.title} ${k} rating`} type="range" min="1" max="5" value={rating[k]} onChange={e=>setRating({...rating,[k]:Number(e.target.value)})}/></label>)}</div><input aria-label={`${recipe.title} Suno URL`} value={url} placeholder="Optional Suno song URL" onChange={e=>setUrl(e.target.value)}/><textarea aria-label={`${recipe.title} outcome notes`} value={note} placeholder="What worked? What surprised you? What changes next?" onChange={e=>setNote(e.target.value)}/><button className="primary" onClick={()=>rate(recipe.id,version.id,rating,note,url)}><Save size={15}/>Preserve outcome</button></article>}

function VaultRoom({vault,setVault,exportNow,importRef,importNow}:{vault:Vault;setVault:(v:Vault)=>void;exportNow:()=>void;importRef:React.RefObject<HTMLInputElement|null>;importNow:(f:File)=>void}){return <Page eyebrow="YOURS ALONE" title="Private Vault" subtitle="No account and no hidden cloud database. Your formulas remain in this browser until you deliberately carry them elsewhere."><section className="vault-cards"><article className="panel"><Download/><h2>Carry the Vault</h2><p>Download one complete portable copy for your laptop, desktop or archive drive.</p><button className="primary" onClick={exportNow}><Download size={15}/>Export complete vault</button></article><article className="panel"><Import/><h2>Restore the Vault</h2><p>Open an Apothecary vault from another computer. This replaces the current local copy.</p><input ref={importRef} hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importNow(e.target.files[0])}/><button onClick={()=>importRef.current?.click()}><Import size={15}/>Import vault</button></article><article className="panel danger"><Trash2/><h2>Empty the Chamber</h2><p>Erase local formulas and return to the original ingredient cabinet.</p><button onClick={()=>confirm("Erase this local Apothecary vault?")&&setVault({...vault,recipes:[]})}><Trash2 size={15}/>Erase formulas</button></article></section><div className="privacy panel"><strong>Privacy architecture</strong><span>Browser-local storage</span><span>Manual portable backups</span><span>No analytics</span><span>No account</span></div></Page>}
function Splitter(){return <Page eyebrow="PRIVATE TWO-STEM ALCHEMY" title="Vocal Splitter" subtitle="Turn a longer Suno song into two useful studio files: the voice and the beat beneath it."><section className="splitter-hero panel"><div><Scissors/><span className="eyebrow">DEMUCS · LOCAL ENGINE</span><h2>Separate the song.<br/><em>Keep the instrumental.</em></h2><p>The separation model runs on your own Windows computer—not inside Vercel and not in a cloud database. Your audio remains private while the dedicated local chamber produces <strong>vocals.wav</strong> and <strong>instrumental-beat.wav</strong>.</p><a href="http://127.0.0.1:47921" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Open Local Vocal Splitter</a></div><ol><li><span>01</span><div><strong>First use only</strong><p>Download the project, then run <code>splitter/setup.ps1</code> to install the private separation engine.</p></div></li><li><span>02</span><div><strong>Begin a session</strong><p>Run <code>splitter/start.ps1</code>. The local splitter opens in your browser.</p></div></li><li><span>03</span><div><strong>Choose the Suno track</strong><p>Select WAV, MP3, FLAC or M4A and press Separate.</p></div></li><li><span>04</span><div><strong>Receive two WAV stems</strong><p>Download the isolated vocal and the instrumental beat.</p></div></li></ol></section><div className="splitter-note"><strong>Why the companion?</strong><p>Studio-grade separation uses a large neural model. Vercel is perfect for the Apothecary interface, but a local engine is faster, more private and free from server time limits.</p></div></Page>}
function Page({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle:string;children:React.ReactNode}){return <section className="page"><header className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></header>{children}</section>}
function Empty({title}:{title:string}){return <div className="empty"><Sparkles/><h2>{title}</h2></div>}
