import { cleanup,render,screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import App from "./App";
beforeEach(()=>{localStorage.clear();vi.spyOn(window,"scrollTo").mockImplementation(()=>undefined);vi.spyOn(URL,"createObjectURL").mockReturnValue("blob:test");vi.spyOn(URL,"revokeObjectURL").mockImplementation(()=>undefined);Object.defineProperty(window,"confirm",{value:vi.fn(()=>true),configurable:true})});afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("Suno Prompt Apothecary",()=>{
 it("offers a beautiful desktop installation path",async()=>{const user=userEvent.setup();render(<App/>);expect(screen.getByRole("button",{name:/Install the Apothecary/i})).toBeTruthy();await user.click(screen.getByRole("button",{name:/Install the Apothecary/i}));expect(screen.getByText(/Open the browser menu and choose Install app/i)).toBeTruthy()});
 it("blends ingredients and seals a versioned recipe",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:/Norse Boom Bap/i}));await user.click(screen.getByRole("button",{name:/Sacred Sensuality/i}));await user.type(screen.getByLabelText("Formula name"),"Freya After Midnight");await user.click(screen.getByRole("button",{name:/Seal in the Grimoire/i}));const vault=JSON.parse(localStorage.getItem("suno-apothecary-v1")||"{}");expect(vault.recipes[0].title).toBe("Freya After Midnight");expect(vault.recipes[0].versions[0].prompt).toContain("Nordic ritual boom bap")});
 it("creates a Cauldron folder and preserves advanced blend controls",async()=>{const user=userEvent.setup();render(<App/>);await user.type(screen.getByLabelText("New folder name"),"Shadow Jazz Sessions");await user.click(screen.getByRole("button",{name:"Create new folder"}));expect((screen.getByLabelText("Cauldron folder") as HTMLSelectElement).value).toBe("Shadow Jazz Sessions");await user.click(screen.getByRole("button",{name:/Shadow Jazz/i}));await user.type(screen.getByLabelText("Tempo BPM"),"82");await user.selectOptions(screen.getByLabelText("Vocal form"),"Spoken Word");await user.type(screen.getByLabelText("Private exclusions"),"no bright pop hooks");await user.type(screen.getByLabelText("Formula name"),"Nocturnal Oracle");await user.click(screen.getByRole("button",{name:/Seal in the Grimoire/i}));const vault=JSON.parse(localStorage.getItem("suno-apothecary-v1")||"{}");expect(vault.collections).toContain("Shadow Jazz Sessions");expect(vault.recipes[0].collection).toBe("Shadow Jazz Sessions");expect(vault.recipes[0].versions[0].prompt).toContain("82 BPM");expect(vault.recipes[0].versions[0].prompt).toContain("spoken word vocals");expect(vault.recipes[0].versions[0].exclusions).toContain("no bright pop hooks")});
 it("autosaves an unfinished Cauldron draft",async()=>{const user=userEvent.setup();const first=render(<App/>);await user.type(screen.getByLabelText("Formula name"),"Unfinished Aurora");await user.type(screen.getByLabelText("Key or mode"),"D Dorian");first.unmount();render(<App/>);expect((screen.getByLabelText("Formula name") as HTMLInputElement).value).toBe("Unfinished Aurora");expect((screen.getByLabelText("Key or mode") as HTMLInputElement).value).toBe("D Dorian")});
 it("creates variants and carries a detailed formula directly into the Prompt Archive",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:/Cinematic Ambient/i}));await user.type(screen.getByLabelText("Formula name"),"Aurora Temple");await user.type(screen.getByLabelText("Key or mode"),"E minor");await user.type(screen.getByLabelText("Target song length"),"6:30");await user.type(screen.getByLabelText("Musical era"),"late 1990s");await user.selectOptions(screen.getByLabelText("Mix profile"),"Cinematic");await user.click(screen.getByText(/Reveal three alternate distillations/i));expect(screen.getByText("VARIANT 3")).toBeTruthy();await user.click(screen.getByRole("button",{name:/Send to Prompt Archive/i}));const vault=JSON.parse(localStorage.getItem("suno-apothecary-v1")||"{}");expect(vault.archivedPrompts[0].title).toBe("Aurora Temple");expect(vault.archivedPrompts[0].prompt).toContain("E minor");expect(vault.archivedPrompts[0].prompt).toContain("6:30 song duration")});
 it("duplicates and downloads a Grimoire formula",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:/Norse Boom Bap/i}));await user.type(screen.getByLabelText("Formula name"),"Iron Freya");await user.click(screen.getByRole("button",{name:/Seal in the Grimoire/i}));await user.click(screen.getByRole("button",{name:"Recipe Grimoire"}));await user.click(screen.getByRole("button",{name:"Duplicate Iron Freya"}));expect(screen.getByText("Iron Freya · Copy")).toBeTruthy();await user.click(screen.getByRole("button",{name:"Download Iron Freya"}));expect(URL.createObjectURL).toHaveBeenCalled()});
 it("adds a custom ingredient",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:"Ingredient Cabinet"}));await user.type(screen.getByLabelText("Ingredient name"),"Moonlit Bass");await user.type(screen.getByLabelText("Ingredient phrase"),"sub bass moving like black water");await user.click(screen.getByRole("button",{name:/Bottle this essence/i}));expect(screen.getByText("Moonlit Bass")).toBeTruthy()});
 it("archives, searches and edits a manually written good prompt",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getByRole("button",{name:"Prompt Archive"}));await user.type(screen.getByLabelText("Archived prompt title"),"Midnight Freya");await user.type(screen.getByLabelText("Archived prompt text"),"Sacred nocturnal jazz with warm goddess whispers");await user.type(screen.getByLabelText("Archived prompt tags"),"jazz, goddess");await user.type(screen.getByLabelText("Archived prompt notes"),"The restraint made the voice feel intimate.");await user.click(screen.getByRole("button",{name:"Archive this prompt"}));expect(screen.getByText("Midnight Freya")).toBeTruthy();expect(JSON.parse(localStorage.getItem("suno-apothecary-v1")||"{}").archivedPrompts).toHaveLength(1);await user.type(screen.getByLabelText("Search prompt archive"),"nocturnal");expect(screen.getByText("Midnight Freya")).toBeTruthy();await user.click(screen.getByRole("button",{name:"Edit Midnight Freya"}));expect(screen.getByRole("button",{name:"Preserve changes"})).toBeTruthy()});
 it("opens every chamber",async()=>{const user=userEvent.setup();render(<App/>);for(const name of ["Ingredient Cabinet","Recipe Grimoire","Prompt Archive","Experiment Chronicle","Vocal Splitter","Private Vault","The Cauldron"]){await user.click(screen.getByRole("button",{name}));expect(screen.getByRole("heading",{name:name==="The Cauldron"?/Distill sound/:name,level:1})).toBeTruthy()}})
});
